// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.MainWindow.SetForegroundWindow(System.IntPtr)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.API.KeyPressAPI.keybd_event(System.Byte,System.Byte,System.UInt32,System.UIntPtr)")]
[assembly: SuppressMessage("Performance", "SYSLIB1045:Convert to 'GeneratedRegexAttribute'.", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.API.MusicAPI.RequestSongID")]
[assembly: SuppressMessage("Performance", "SYSLIB1045:Convert to 'GeneratedRegexAttribute'.", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.API.MusicAPI.GetLyrics")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.BTBatteryIndividual.Page_Loaded(System.Object,Microsoft.UI.Xaml.RoutedEventArgs)")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.IndividualMonitor.GetMonitorBrightness(System.IntPtr,System.UInt32@,System.UInt32@,System.UInt32@)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.IndividualMonitor.SetMonitorBrightness(System.IntPtr,System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.LyricsView.GetWindowLong(System.IntPtr,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.LyricsView.SetWindowLong(System.IntPtr,System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.LyricsView.SetWindowPos(System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32,System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.ClassImplementations.SharedPages.NORC_WidgetApps.SHGetFileInfo(System.String,System.UInt32,CompanionDisplayWinUI.ClassImplementations.SharedPages.NORC_WidgetApps.SHFILEINFO@,System.UInt32,System.UInt32)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.PopupWidget.GetDpiForWindow(System.IntPtr)~System.UInt32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.PopupWidget.GetWindowLong(System.IntPtr,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.PopupWidget.SetWindowLong(System.IntPtr,System.Int32,System.Int32)~System.Int32")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:CompanionDisplayWinUI.PopupWidget.SetWindowPos(System.IntPtr,System.IntPtr,System.Int32,System.Int32,System.Int32,System.Int32,System.UInt32)~System.Boolean")]
